#!/bin/bash
set -e

service postgresql start

/etc/init.d/xvfb start

pushd postfacto-web
    npm install
    export PATH=$PATH:./node_modules/.bin
popd

pushd postfacto-api
    bundle install --path vendor/bundle
popd

pushd postfacto-web/acceptance
    bundle install --path vendor/bundle
popd

cd postfacto-web
API_DIR=postfacto-api gulp local-acceptance
